name: noteapp_note_command_service
version: "0.1.0"
author: CG  <abc@abc.com>
about: Note App
args:
    - domain:
        short: d
        long: domain
        env: DOMAIN
        value_name: Domain
        required: true
        about: Sets domain of microservice
        default_value: 127.0.0.1
        takes_value: true
    - port:
        short: o
        long: port
        env: SERVICE_PORT
        value_name: PORT
        required: true
        about: Sets port of microservice
        default_value: "8080"
        takes_value: true
    - kafka-brokers-addr:
        short: b
        long: kafka-brokers-addr
        env: KAFKA_BROKERS_ADDR
        value_name: KAFKA_BROKERS_ADDR
        required: true
        default_value: localhost:9092
        about: Sets address of kafka brokers
        takes_value: true
    - kafka-producer-topics:
        short: t
        long: kafka-producer-topics
        env: KAFKA_PRODUCER_TOPICS
        value_name: KAFKA_PRODUCER_TOPICS
        required: true
        default_value: note.command.service
        about: Sets producer topics of kafka
        takes_value: true
    - eventstore-host-with-parameters:
        short: h
        long: eventstore-host-with-parameters
        env: EVENTSTORE_HOST_WITH_PARAMETERS
        value_name: EVENTSTORE_HOST_WITH_PARAMETERS
        required: true
        about: Sets host string of eventstore
        default_value: localhost:2113?tls=false
        takes_value: true
    - eventstore-username:
        short: u
        long: eventstore-username
        env: EVENTSTORE_USERNAME
        value_name: EVENTSTORE_USERNAME
        required: true
        about: Sets username of eventstore
        default_value: admin
        takes_value: true
    - eventstore-password:
        short: p
        long: eventstore-password
        env: EVENTSTORE_PASSWORD
        value_name: EVENTSTORE_PASSWORD
        required: true
        about: Sets password of eventstore
        default_value: changeit
        takes_value: true